# Generated by Django 5.0.6 on 2024-06-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="phone_number",
            new_name="phone",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
