# Generated by Django 5.0.6 on 2024-06-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, default="regular", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[(None, "선택"), ("일반회원", "일반회원"), ("기업회원", "기업회원")],
                default="선택",
                max_length=10,
            ),
        ),
    ]
