# Generated by Django 5.0.6 on 2024-07-02 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_booth_date_edit_profile_booth_name_edit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="booth_date_edit",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="booth_name_edit",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="booth_pic_edit",
        ),
    ]
