# Generated by Django 5.0.6 on 2024-07-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booth_Info",
            fields=[
                (
                    "booth_id",
                    models.IntegerField(
                        db_column="BoothID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "booth_name",
                    models.TextField(blank=True, db_column="BoothName", null=True),
                ),
                (
                    "company_id",
                    models.IntegerField(blank=True, db_column="CompanyID", null=True),
                ),
                (
                    "company_name",
                    models.TextField(blank=True, db_column="CompanyName", null=True),
                ),
                (
                    "exhibition_id",
                    models.IntegerField(
                        blank=True, db_column="ExhibitionID", null=True
                    ),
                ),
                (
                    "booth_category",
                    models.TextField(
                        blank=True, db_column="ExhibitionCategory", null=True
                    ),
                ),
                (
                    "background",
                    models.TextField(
                        blank=True, db_column="BoothDescription1", null=True
                    ),
                ),
                (
                    "service",
                    models.TextField(
                        blank=True, db_column="BoothDescription2", null=True
                    ),
                ),
            ],
            options={
                "db_table": "Booth_Info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="faq_aivle",
            fields=[
                (
                    "qapk",
                    models.TextField(
                        db_column="qapk", primary_key=True, serialize=False
                    ),
                ),
                ("qacust", models.TextField(blank=True, db_column="qacust")),
                ("qacat", models.TextField(blank=True, db_column="qacat")),
                ("qalist", models.TextField(blank=True, db_column="qalist")),
                ("source", models.TextField(blank=True, db_column="source", null=True)),
            ],
            options={
                "db_table": "chat_faq_aivle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="faq_exhi",
            fields=[
                (
                    "qapk",
                    models.TextField(
                        db_column="qapk", primary_key=True, serialize=False
                    ),
                ),
                ("qacust", models.TextField(blank=True, db_column="qacust")),
                ("qacat", models.TextField(blank=True, db_column="qacat")),
                ("qalist", models.TextField(blank=True, db_column="qalist")),
                ("source", models.TextField(blank=True, db_column="source", null=True)),
            ],
            options={
                "db_table": "chat_faq_exhi",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
