# Generated by Django 5.0.6 on 2024-07-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="faq_aivle",
            fields=[
                (
                    "qapk",
                    models.TextField(
                        db_column="qapk", primary_key=True, serialize=False
                    ),
                ),
                ("qacust", models.TextField(blank=True, db_column="qacust")),
                ("qacat", models.TextField(blank=True, db_column="qacat")),
                ("qalist", models.TextField(blank=True, db_column="qalist")),
                ("source", models.TextField(blank=True, db_column="source", null=True)),
            ],
            options={
                "db_table": "chat_faq_aivle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="faq_exhi",
            fields=[
                (
                    "qapk",
                    models.TextField(
                        db_column="qapk", primary_key=True, serialize=False
                    ),
                ),
                ("qacust", models.TextField(blank=True, db_column="qacust")),
                ("qacat", models.TextField(blank=True, db_column="qacat")),
                ("qalist", models.TextField(blank=True, db_column="qalist")),
                ("source", models.TextField(blank=True, db_column="source", null=True)),
            ],
            options={
                "db_table": "chat_faq_exhi",
                "managed": False,
            },
        ),
    ]
