# Generated by Django 5.0.6 on 2024-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booth_Info",
            fields=[
                (
                    "booth_id",
                    models.IntegerField(
                        db_column="BoothID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "booth_name",
                    models.TextField(blank=True, db_column="BoothName", null=True),
                ),
                (
                    "company_id",
                    models.IntegerField(blank=True, db_column="CompanyID", null=True),
                ),
                (
                    "company_name",
                    models.TextField(blank=True, db_column="CompanyName", null=True),
                ),
                (
                    "exhibition_id",
                    models.IntegerField(
                        blank=True, db_column="ExhibitionID", null=True
                    ),
                ),
                (
                    "booth_category",
                    models.TextField(
                        blank=True, db_column="ExhibitionCategory", null=True
                    ),
                ),
                (
                    "background",
                    models.TextField(
                        blank=True, db_column="BoothDescription1", null=True
                    ),
                ),
                (
                    "service",
                    models.TextField(
                        blank=True, db_column="BoothDescription2", null=True
                    ),
                ),
            ],
            options={
                "db_table": "Booth_Info",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="chathistory",
            options={},
        ),
    ]
