# Generated by Django 5.0.6 on 2024-07-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0002_djangosession"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exhibition_info",
            fields=[
                (
                    "exhibition_id",
                    models.AutoField(
                        db_column="ExhibitionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "exhibition_name",
                    models.CharField(db_column="ExhibitionName", max_length=100),
                ),
                (
                    "exhibition_description",
                    models.CharField(db_column="ExhibitionDescription", max_length=100),
                ),
                (
                    "start_date",
                    models.DateField(db_column="ExhibitionRegistrationDate"),
                ),
                (
                    "host_id",
                    models.IntegerField(db_column="OrganizationID", unique=True),
                ),
                (
                    "hall_id",
                    models.CharField(
                        choices=[
                            ("", "선택"),
                            ("1", "A홀"),
                            ("2", "B홀"),
                            ("3", "C홀"),
                            ("4", "D홀"),
                        ],
                        db_column="Hall_ID",
                        default="",
                        max_length=50,
                    ),
                ),
                ("end_date", models.DateField(db_column="ExhibitionClosedDate")),
            ],
            options={
                "db_table": "Exhibition_info",
                "managed": False,
            },
        ),
    ]
