# Generated by Django 5.0.6 on 2024-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="faq_aivle",
            fields=[
                (
                    "qapk",
                    models.TextField(
                        db_column="qapk", primary_key=True, serialize=False
                    ),
                ),
                ("qacust", models.TextField(blank=True, db_column="qacust")),
                ("qacat", models.TextField(blank=True, db_column="qacat")),
                ("qalist", models.TextField(blank=True, db_column="qalist")),
                ("source", models.TextField(blank=True, db_column="source", null=True)),
            ],
            options={
                "db_table": "chat_faq_aivle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="faq_exhi",
            fields=[
                (
                    "qapk",
                    models.TextField(
                        db_column="qapk", primary_key=True, serialize=False
                    ),
                ),
                ("qacust", models.TextField(blank=True, db_column="qacust")),
                ("qacat", models.TextField(blank=True, db_column="qacat")),
                ("qalist", models.TextField(blank=True, db_column="qalist")),
                ("source", models.TextField(blank=True, db_column="source", null=True)),
            ],
            options={
                "db_table": "chat_faq_exhi",
                "managed": False,
            },
        ),
    ]
