# Generated by Django 5.0.6 on 2024-07-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
