# Generated by Django 5.0.6 on 2024-07-15 01:11

import notice.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0002_alter_notice_update_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="filename",
            field=models.CharField(max_length=64, null=True, verbose_name="첨부파일명"),
        ),
        migrations.AddField(
            model_name="notice",
            name="upload_files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=notice.models.get_file_path,
                verbose_name="파일",
            ),
        ),
    ]
