# Generated by Django 5.0.6 on 2024-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booth_Info",
            fields=[
                (
                    "booth_id",
                    models.IntegerField(
                        db_column="BoothID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "booth_name",
                    models.TextField(blank=True, db_column="BoothName", null=True),
                ),
                (
                    "company_id",
                    models.IntegerField(blank=True, db_column="CompanyID", null=True),
                ),
                (
                    "company_name",
                    models.TextField(blank=True, db_column="CompanyName", null=True),
                ),
                (
                    "exhibition_id",
                    models.IntegerField(
                        blank=True, db_column="ExhibitionID", null=True
                    ),
                ),
                (
                    "booth_category",
                    models.TextField(
                        blank=True, db_column="ExhibitionCategory", null=True
                    ),
                ),
                (
                    "background",
                    models.TextField(
                        blank=True, db_column="BoothDescription1", null=True
                    ),
                ),
                (
                    "service",
                    models.TextField(
                        blank=True, db_column="BoothDescription2", null=True
                    ),
                ),
            ],
            options={
                "db_table": "Booth_Info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "exhibition_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("host_id", models.CharField(max_length=50)),
                (
                    "hall",
                    models.CharField(
                        choices=[("", "선택"), ("A홀", "A홀"), ("B홀", "B홀"), ("C홀", "C홀")],
                        default="",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("number_of_booths", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "exhibition_exhibition",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="exhibition/")),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
