# Generated by Django 5.0.6 on 2024-07-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="exbooth_1st",
            fields=[
                (
                    "group",
                    models.TextField(
                        db_column="group", primary_key=True, serialize=False
                    ),
                ),
                ("bname", models.TextField(blank=True, db_column="bname")),
                ("bcat", models.TextField(blank=True, db_column="bcat")),
                (
                    "background",
                    models.TextField(blank=True, db_column="background", null=True),
                ),
                (
                    "service",
                    models.TextField(blank=True, db_column="service", null=True),
                ),
            ],
            options={
                "db_table": "exbooth_1st",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="exbooth_2nd",
            fields=[
                (
                    "group",
                    models.TextField(
                        db_column="group", primary_key=True, serialize=False
                    ),
                ),
                ("bname", models.TextField(blank=True, db_column="bname")),
                ("bcat", models.TextField(blank=True, db_column="bcat")),
                (
                    "background",
                    models.TextField(blank=True, db_column="background", null=True),
                ),
                (
                    "service",
                    models.TextField(blank=True, db_column="service", null=True),
                ),
            ],
            options={
                "db_table": "exbooth_2nd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="exbooth_3rd",
            fields=[
                (
                    "group",
                    models.TextField(
                        db_column="group", primary_key=True, serialize=False
                    ),
                ),
                ("bname", models.TextField(blank=True, db_column="bname")),
                ("bcat", models.TextField(blank=True, db_column="bcat")),
                (
                    "background",
                    models.TextField(blank=True, db_column="background", null=True),
                ),
                (
                    "service",
                    models.TextField(blank=True, db_column="service", null=True),
                ),
            ],
            options={
                "db_table": "exbooth_3rd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="exbooth_4th",
            fields=[
                (
                    "group",
                    models.TextField(
                        db_column="group", primary_key=True, serialize=False
                    ),
                ),
                ("bname", models.TextField(blank=True, db_column="bname")),
                ("bcat", models.TextField(blank=True, db_column="bcat")),
                (
                    "background",
                    models.TextField(blank=True, db_column="background", null=True),
                ),
                (
                    "service",
                    models.TextField(blank=True, db_column="service", null=True),
                ),
            ],
            options={
                "db_table": "exbooth_4th",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="exhibition/")),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
