# Generated by Django 5.0.6 on 2024-07-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "exhibition_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("host_id", models.CharField(max_length=50)),
                (
                    "hall",
                    models.CharField(
                        choices=[
                            (None, "선택"),
                            ("A홀", "A홀"),
                            ("B홀", "B홀"),
                            ("C홀", "C홀"),
                        ],
                        default="선택",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("number_of_booths", models.IntegerField(default=0)),
            ],
        ),
    ]
