# Generated by Django 5.0.6 on 2024-07-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibition", "0002_exhibition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="hall",
            field=models.CharField(
                choices=[("", "선택"), ("A홀", "A홀"), ("B홀", "B홀"), ("C홀", "C홀")],
                default="",
                max_length=50,
            ),
        ),
    ]
