# Generated by Django 5.0.6 on 2024-07-08 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibition", "0003_alter_exhibition_hall"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exhibition",
            options={"managed": False},
        ),
    ]
