# Generated by Django 5.0.6 on 2024-07-08 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibition", "0004_exhibition_info_alter_exhibition_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="exhibition",
            table="exhibition_exhibition",
        ),
    ]
