# Generated by Django 5.0.6 on 2024-07-08 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibition", "0004_alter_exhibition_options"),
        ("exhibition", "0005_alter_exhibition_table"),
    ]

    operations = []
