# Generated by Django 5.0.6 on 2024-07-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth_program", "0002_booth_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="company_name",
            field=models.CharField(default="default_company", max_length=100),
        ),
    ]
