# Generated by Django 5.0.6 on 2024-07-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booth_program", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoothProgramReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("program_name", models.CharField(max_length=200)),
                ("num_of_people", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ReservationTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reserved_time", models.CharField(max_length=100)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booth_program.boothprogramreservation",
                    ),
                ),
            ],
        ),
    ]
